modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheCSDev/mc-better-stats/issues" #optional

[[mods]] #mandatory
displayName="Better Statistics Screen" #mandatory
modId="betterstats" #mandatory
version="2.2.1+1.19.2" #mandatory
authors="TheCSDev" #optional
credits="See authors." #optional
displayURL="https://github.com/TheCSDev/mc-better-stats" #optional
logoFile="betterstats_icon.png" #optional
description='''Improves the statistics screen and makes it more useful.'''

[[dependencies.betterstats]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.betterstats]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterstats]] #optional
    modId="tcdcommons" #mandatory
    mandatory=true #mandatory
    versionRange="[2,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="BEFORE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"